name: s390x-node18-nginx-certbot

on:
  push:
    tags: 
      - nginxcertbot*
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Check out

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: |
            linux/s390x
          push: true
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            NginxNodeCertbot
     run: docker build . --file Dockerfile --tag s390x-node18-nginx-certbot:$(date +%s)
